https://pythonhosted.org/pyDOE/rsm.html

# Response Surface Designs

In this section, the following kinds of response surface designs will be described:

- Box-Behnken

- Central Composite

>Hint: All available designs can be accessed after a simple import statement:

In [1]:
# pip install --upgrade pyDOE2

In [1]:
# from pyDOE import *
from pyDOE2 import *
import numpy as np
import pandas as pd

## Box-Behnken (`bbdesign`)

http://www.itl.nist.gov/div898/handbook/pri/section3/gifs/bb.gif

Box-Behnken designs can be created using the following simple syntax:

```
bbdesign(n, center)
```

where n is the number of factors (at least 3 required) and center is the number of center points to include. If no inputs given to center, then a pre-determined number of points are automatically included.

## Examples

The default 3-factor Box-Behnken design:

In [3]:
bbd3 = bbdesign(3)
bbd3

array([[-1., -1.,  0.],
       [ 1., -1.,  0.],
       [-1.,  1.,  0.],
       [ 1.,  1.,  0.],
       [-1.,  0., -1.],
       [ 1.,  0., -1.],
       [-1.,  0.,  1.],
       [ 1.,  0.,  1.],
       [ 0., -1., -1.],
       [ 0.,  1., -1.],
       [ 0., -1.,  1.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
bbd3.shape

(15, 3)

In [4]:
np.corrcoef(bbd3.T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

A customized design with four factors, but only a single center point:

In [5]:
bbd4_1 = bbdesign(4, center=1)
bbd4_1

array([[-1., -1.,  0.,  0.],
       [ 1., -1.,  0.,  0.],
       [-1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [-1.,  0., -1.,  0.],
       [ 1.,  0., -1.,  0.],
       [-1.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  0.],
       [-1.,  0.,  0., -1.],
       [ 1.,  0.,  0., -1.],
       [-1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 0., -1., -1.,  0.],
       [ 0.,  1., -1.,  0.],
       [ 0., -1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.],
       [ 0., -1.,  0., -1.],
       [ 0.,  1.,  0., -1.],
       [ 0., -1.,  0.,  1.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  0., -1., -1.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0., -1.,  1.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
bbd4_1.shape

(25, 4)

In [6]:
np.corrcoef(bbd4_1.T)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Central Composite (`ccdesign`)

http://www.itl.nist.gov/div898/handbook/pri/section3/gifs/fig5.gif

Central composite designs can be created and customized using the syntax:

```
ccdesign(n, center, alpha, face)
```

where

- `n` is the number of factors,

- `center` is a 2-tuple of center points (one for the factorial block, one for the star block, default (4, 4)),

- `alpha` is either “orthogonal” (or “o”, default) or “rotatable” (or “r”)

- `face` is either “circumscribed” (or “ccc”, default), “inscribed” (or “cci”), or “faced” (or “ccf”).

http://www.itl.nist.gov/div898/handbook/pri/section3/gifs/ccd2.gif

The two optional keyword arguments alpha and face help describe how the variance in the quadratic approximation is distributed. Please see the NIST web pages if you are uncertain which options are suitable for your situation.

Note:

- ‘ccc’ and ‘cci’ can be rotatable designs, but ‘ccf’ cannot

- If face is specified, while alpha is not, then the default value of alpha is ‘orthogonal’

## Examples

Simplest input, assuming default kwargs:

In [7]:
ccd2 = ccdesign(2)
ccd2

array([[-1.        , -1.        ],
       [ 1.        , -1.        ],
       [-1.        ,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-1.41421356,  0.        ],
       [ 1.41421356,  0.        ],
       [ 0.        , -1.41421356],
       [ 0.        ,  1.41421356],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [10]:
ccd2.shape

(16, 2)

In [8]:
np.corrcoef(ccd2.T)

array([[1., 0.],
       [0., 1.]])

More customized input, say, for a set of computer experiments where there isn’t variability so we only need a single center point:

In [13]:
ccd3 = ccdesign(3, center=(0, 1), alpha='r', face='cci')
ccd3

array([[-0.59460356, -0.59460356, -0.59460356],
       [ 0.59460356, -0.59460356, -0.59460356],
       [-0.59460356,  0.59460356, -0.59460356],
       [ 0.59460356,  0.59460356, -0.59460356],
       [-0.59460356, -0.59460356,  0.59460356],
       [ 0.59460356, -0.59460356,  0.59460356],
       [-0.59460356,  0.59460356,  0.59460356],
       [ 0.59460356,  0.59460356,  0.59460356],
       [-1.        ,  0.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        , -1.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [14]:
ccd3.shape

(15, 3)

In [15]:
np.corrcoef(ccd3.T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## More Information

If the user needs more information about appropriate designs, please consult the following articles on Wikipedia:

- Box-Behnken designs
    + http://en.wikipedia.org/wiki/Box-Behnken_design

- Central composite designs
    + http://en.wikipedia.org/wiki/Central_composite_design

There is also a wealth of information on the NIST website about the various design matrices that can be created as well as detailed information about designing/setting-up/running experiments in general:

http://www.itl.nist.gov/div898/handbook/pri/pri.htm

Any questions, comments, bug-fixes, etc. can be forwarded to the [author](tisimst@gmail.com).

### Create 3 Factor RSM

http://reliawiki.org/index.php/Response_Surface_Methods_for_Optimization

In [16]:
doe_m = ccdesign(3, center=(0, 1), alpha='r', face='cci')
doe_m.shape

(15, 3)

In [17]:
doe_df = pd.DataFrame(doe_m)
doe_df.shape

(15, 3)

In [18]:
doe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       15 non-null     float64
 1   1       15 non-null     float64
 2   2       15 non-null     float64
dtypes: float64(3)
memory usage: 488.0 bytes


In [19]:
doe_df.columns = ['A', 'B', 'C']
doe_df.head()

A         B         C
0 -0.594604 -0.594604 -0.594604
1  0.594604 -0.594604 -0.594604
2 -0.594604  0.594604 -0.594604
3  0.594604  0.594604 -0.594604
4 -0.594604 -0.594604  0.594604

In [20]:
doe_df.corr()

A    B    C
A  1.0  0.0  0.0
B  0.0  1.0  0.0
C  0.0  0.0  1.0

In [21]:
doe_df['AB'] = doe_df['A'] * doe_df['B']
doe_df['AC'] = doe_df['A'] * doe_df['C']
doe_df['BC'] = doe_df['B'] * doe_df['C']

doe_df['ABC'] = doe_df['A'] * doe_df['B'] * doe_df['C']

doe_df['A2'] = doe_df['A'] * doe_df['A']
doe_df['B2'] = doe_df['B'] * doe_df['B']
doe_df['C2'] = doe_df['C'] * doe_df['C']

In [27]:
np.round(doe_df.corr(), 3)

A    B    C   AB   AC   BC  ABC     A2     B2     C2
A    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000  0.000  0.000
B    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.000  0.000  0.000
C    0.0  0.0  1.0  0.0  0.0  0.0  0.0 -0.000 -0.000 -0.000
AB   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.000  0.000  0.000
AC   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.000  0.000  0.000
BC   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.000  0.000  0.000
ABC  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.000  0.000  0.000
A2   0.0  0.0 -0.0  0.0  0.0  0.0  0.0  1.000 -0.383 -0.383
B2   0.0  0.0 -0.0  0.0  0.0  0.0  0.0 -0.383  1.000 -0.383
C2   0.0  0.0 -0.0  0.0  0.0  0.0  0.0 -0.383 -0.383  1.000

In [40]:
use_doe = doe_df[['A', 'B', 'C']]
use_doe

A         B         C
0  -0.594604 -0.594604 -0.594604
1   0.594604 -0.594604 -0.594604
2  -0.594604  0.594604 -0.594604
3   0.594604  0.594604 -0.594604
4  -0.594604 -0.594604  0.594604
5   0.594604 -0.594604  0.594604
6  -0.594604  0.594604  0.594604
7   0.594604  0.594604  0.594604
8  -1.000000  0.000000  0.000000
9   1.000000  0.000000  0.000000
10  0.000000 -1.000000  0.000000
11  0.000000  1.000000  0.000000
12  0.000000  0.000000 -1.000000
13  0.000000  0.000000  1.000000
14  0.000000  0.000000  0.000000

In [41]:
new_names = ['mp', 'cp', 'pp']
        
use_doe2 = use_doe.copy()
use_doe2.columns = new_names

use_doe2

mp        cp        pp
0  -0.594604 -0.594604 -0.594604
1   0.594604 -0.594604 -0.594604
2  -0.594604  0.594604 -0.594604
3   0.594604  0.594604 -0.594604
4  -0.594604 -0.594604  0.594604
5   0.594604 -0.594604  0.594604
6  -0.594604  0.594604  0.594604
7   0.594604  0.594604  0.594604
8  -1.000000  0.000000  0.000000
9   1.000000  0.000000  0.000000
10  0.000000 -1.000000  0.000000
11  0.000000  1.000000  0.000000
12  0.000000  0.000000 -1.000000
13  0.000000  0.000000  1.000000
14  0.000000  0.000000  0.000000

In [42]:
# map min_x = -1 to min_y and max_x = 1 to max_y

min_x = -1.0
max_x =  1.0

min_y = 0.1
max_y = 0.9

# Y = m*X + b
# m = dy/dx
# b = Y - m*x
slope = (max_y - min_y)/(max_x - min_x)
intercept = max_y - slope*max_x

In [43]:
use_doe2['mp'] = slope*use_doe2['mp'] + intercept
use_doe2['cp'] = slope*use_doe2['cp'] + intercept
use_doe2['pp'] = slope*use_doe2['pp'] + intercept

In [44]:
use_doe2

mp        cp        pp
0   0.262159  0.262159  0.262159
1   0.737841  0.262159  0.262159
2   0.262159  0.737841  0.262159
3   0.737841  0.737841  0.262159
4   0.262159  0.262159  0.737841
5   0.737841  0.262159  0.737841
6   0.262159  0.737841  0.737841
7   0.737841  0.737841  0.737841
8   0.100000  0.500000  0.500000
9   0.900000  0.500000  0.500000
10  0.500000  0.100000  0.500000
11  0.500000  0.900000  0.500000
12  0.500000  0.500000  0.100000
13  0.500000  0.500000  0.900000
14  0.500000  0.500000  0.500000

In [45]:
np.round(use_doe2.corr(), 3)

mp   cp   pp
mp  1.0  0.0  0.0
cp  0.0  1.0  0.0
pp  0.0  0.0  1.0

In [46]:
use_doe2.to_csv('hpt_rsm1.csv', index=False)